server:
  port: 8081
  context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/egc_dev
    username: egcuser
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


resultState:
  success:1
  failed:2